name: brief_reading
description: Simple reading app developed using Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 状态管理 https://pub.flutter-io.cn/packages/fish_redux
  fish_redux: ^0.3.7
  # https://pub.flutter-io.cn/packages/adaptive_breakpoints
  # 根据窗口大小自展示布局
  adaptive_breakpoints: ^0.0.4
  # Flutter预置的高质量动画 https://pub.flutter-io.cn/packages/animations
  animations: ^2.0.0
  # 集合操作 https://pub.flutter-io.cn/packages/collection
  collection: ^1.15.0
  # Images, fonts, and videos used in the Flutter Gallery app
  #  flutter_gallery_assets: ^1.0.2
  #  shrine_images: ^2.0.1
  #  rally_assets: ^3.0.1

  # https://pub.flutter-io.cn/packages/flutter_localized_locales
  # 它可以从 563 语言环境的语言环境代码（ISO 639‑2 和 ISO 639-3）中获取本地化语言环境名称。
  flutter_localized_locales: ^2.0.1
  # https://pub.flutter-io.cn/packages/flutter_staggered_grid_view
  # Flutter 交错网格视图，支持多列和不同大小的行。
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^2.0.0
  # 国际化
  intl: ^0.17.0
  # 静态分析注解 https://pub.flutter-io.cn/packages/meta
  # 这个包定义了可以被 Dart SDK 附带的工具使用的注释。
  meta: ^1.3.0
  # 查询应用包信息 https://pub.flutter-io.cn/packages/package_info_plus
  package_info_plus: ^1.0.1
  # 一组实用程序，可让您轻松地将数据模型从父 Widget 传递到其后代。此外，它还会在模型更新时重建所有使用该模型的子代。这个库最初是从 Fuchsia 代码库中提取的。
  # https://pub.flutter-io.cn/packages/scoped_model
  scoped_model: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.3
  # A Vector math library for 2D and 3D applications.
  # https://pub.flutter-io.cn/packages/vector_math
  vector_math: ^2.1.0
  # https://pub.flutter-io.cn/packages/fradio
  fradio: ^1.0.1
  # https://pub.flutter-io.cn/packages/ffloat
  ffloat: ^1.0.1

  # 图表 https://pub.flutter-io.cn/packages/charts_flutter
  charts_flutter: ^0.10.0

  # 下拉刷新 https://pub.flutter-io.cn/packages/flutter_easyrefresh
  flutter_easyrefresh: ^2.2.1
  fbutton: 2.0.1

  # https://pub.flutter-io.cn/packages/ftoast
  ftoast: ^1.0.0

  # https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.0.0+2

  # requires permission configuration to Android- and iOS-specific files.
  # https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^8.0.0+2

  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - images/